version: '3.9'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://user:password@db/app
      GMAIL_USER: yourgmail@example.com
      GMAIL_PASS: yourgmailpassword
      ENCRYPTION_KEY: yourverysecretkeybase64==
      SECRET_KEY: changeme
    depends_on:
      - db
volumes:
  db_data:
